cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
cat sp2.cql | cypher-shell -u neo4j -p password --format plain >> sp2/sp_0
