cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
cat kneighbors.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors1/kneighbors_0
