cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
cat sp.cql | cypher-shell -u neo4j -p password --format plain >> sp1/sp_0
