cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
cat kneighbors2.cql | cypher-shell -u neo4j -p password --format plain >> kneighbors2/kneighbors_0
